services:
  web:
    build: .
    container_name: farm-web
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - PUBLIC_API_BASE=/api # Frontend calls same-origin
    ports:
      - '1700:3000' # host:container — visit http://localhost:1700
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: farm-tunnel
    restart: unless-stopped
    # Use either a TUNNEL_TOKEN *or* mount credentials (shown here)
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    depends_on: [web]
